#!/bin/bash

inputfile="output.txt"
output="output-wiki.txt"
output_ok="output-ok.txt"
output_http="output-http.txt"
output_ftp="output-ftp.txt"
output_robots="output-robots.txt"
output_websites="active-websites.txt"
output_prod="output-prod.txt"
input_wiki="current-websites.txt"
exec `sort -o $inputfile $inputfile`
exec `cat /dev/null > $output`
exec `cat /dev/null > $output_http`
exec `cat /dev/null > $output_ftp`
exec `cat /dev/null > $output_ok`
exec `cat /dev/null > $output_websites`

total_websites=0
total_analytics=0
total_ok=0
total_error=0
total_redirect=0
total_ftp=0
total_robots_blocked=0
total_prod=0

curl -s https://wiki.mozilla.org/Websites/Active_List > $input_wiki

dev_domains="allizom|cdn\-|\-cdn|\.stage|\-stage|stage\-|stage\."

today=`date +%m-%d-%Y`

echo "The following is a list of active websites that are blocked from ALL robot spidering:
" > $output_robots

echo "== Domain List ==

The following list and updates is as of $today.

	{| class='wikitable sortable' border='1'
	|-
	! scope='col' | Web Address
	! scope='col' | Status
	! scope='col' | Analytics Installed
	! scope='col' | Analytics Page Coverage" > $output

input=`cat $inputfile`

for thisline in $input; do
	
	IFS=","
	var=$thisline
	set -- $var
	
	address=$1
	pro=$2
	status=`echo $3 | sed 's/\+/ /g'` 
	status_type=$4
	analytics=$5
	coverage=$6

	echo "|-" >> $output 

	if [ "$status_type" == "ok" ]; then
		(( total_ok++ ))
		robots=`./check-robots.sh $address`
		if [ "$robots" == "1" ]; then
			(( total_robots_blocked++ ))
			echo "* [$pro://$address $address]" >> $output_robots
		fi

		ignore_domain_check=`echo $address | grep -i -E $dev_domains | wc -l | sed 's/ //g'`		

		if [ $ignore_domain_check == 0 ]; then
			(( total_prod++ ))
			echo "* $address" >> $output_prod
		fi

		address_check=`./get-redirected-address.sh $address`
		echo "Check: $address, $address_check"
		exec `./active-websites.sh $address_check $input_wiki $output_websites > /dev/null`
		echo "* $address" >> $output_ok

	elif [ "$status_type" == "error" ]; then
		(( total_error++ ))
	elif [ "$status_type" == "redirect" ]; then
		(( total_redirect++ ))
	fi
	
	if [[ "$pro" == "ftp" ]]; then
		(( total_ftp++ ))
		echo "* $address" >> $output_ftp
	else
		(( total_websites++ ))
		echo "* $address" >> $output_http
	fi
	
	if [ "$analytics" == "Yes" ]; then
		(( total_analytics++ ))
	fi
	
	if [ "$coverage" != "N/A" ]; then
		coverage="$coverage%"
	fi
	
	echo "| [$pro://$address $address] || $status || $analytics || $coverage" >> $output

done

echo "|}

== Statistics ==

* Total domains: [[Websites/Domain_List/http|$total_websites]]
* Total ok: [[Websites/Domain_List/ok|$total_ok]]
* Total prod: [[Websites/Domain_List/prod|$total_prod]]
* Total errors: $total_error
* Total redirects: $total_redirect
* Total analytics installed: $total_analytics
* Total robot blocked websites: [[Websites/Domain_List/robots-blocked|$total_robots_blocked]]

== Do you have changes to this list? ==

This wiki page is automatically generated by scripts. Please contact [https://ldap.mozilla.org/phonebook/tree.php#search/cmore@mozilla.com Chris More] for more 
information. The source script for this page can be found [https://github.com/chrismore/Domain-Name-Status-Checker here]." >> $output
